export const ENV = {
  GRAPHQL_URL: import.meta.env.VITE_PUBLIC_GRAPHQL_URL,
  GRAPHQL_WS: import.meta.env.VITE_PUBLIC_GRAPHQL_WS,
  RPC_WEBSOCKET: import.meta.env.VITE_PUBLIC_RPC_WEBSOCKET,
  WS_CHAIN_URL: import.meta.env.VITE_PUBLIC_WS_CHAIN_URL,
  CHAIN_TYPE: import.meta.env.VITE_PUBLIC_CHAIN_TYPE,
  CHAIN_STATUS: import.meta.env.VITE_PUBLIC_CHAIN_STATUS,
  REST_CHAIN_URL: import.meta.env.VITE_PUBLIC_REST_CHAIN_URL,
  VALIDATORS_IDENTITY_LIST_URL: import.meta.env
    .VITE_PUBLIC_VALIDATORS_IDENTITY_LIST_URL,
  IGNORE_LIST_URL: import.meta.env.VITE_PUBLIC_IGNORE_LIST_URL,
};
